groups:
  - name: alert_rules
    interval: 1s
    rules:
    - alert: container_not_running
      expr: |
        time() - container_last_seen{name="grafana"} > 10
          or
        time() - container_last_seen{name="app"} > 10
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Container "{{ $labels.name }}" is not running
        description: 'container "{{ $labels.name }}" has been down for more than {{ $value | printf "%.0f" }}'
    - alert: lot_of_coin_flips
      expr: rate(flip_count{job="app"}[1m]) *60 >1000
      for: 1s
      labels:
        severity: critical
      annotations:
        summary: The coin flip server has lot of coin flips
        description: 'An estimated {{ $value | printf "%.0f" }} coins have been flipped in the last min'