{
 "title": "Express app dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()- process_start_time_seconds{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flips per min",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(flip_count{job=\"app\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tails per flip",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tails_count{job=\"app\"} / flip_count{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heads per flip",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heads_count{job=\"app\"}/flip_count{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}